

essai1:
	/usr/ccs/lib/cpp -P essai1.cim essai1.cpp
	/users/demons/contejea/cime/src/main -confl essai1.cpp
toto:
	/usr/ccs/lib/cpp -P toto.cim toto.cpp
	/users/demons/contejea/cime/src/main -confl toto.cpp

titi:
	/usr/ccs/lib/cpp -P titi.cim titi.cpp
	/users/demons/contejea/cime/src/main -confl titi.cpp

bool:
	/usr/ccs/lib/cpp -P bool.cim bool.cpp
	/users/demons/contejea/cime/src/main -confl bool.cpp

posnat-base3:
	/usr/ccs/lib/cpp -P posnat-base3.cim posnat-base3.cpp
	/users/demons/contejea/cime/src/main -confl posnat-base3.cpp

int-base3:
	/usr/ccs/lib/cpp -P int-base3.cim int-base3.cpp
	/users/demons/contejea/cime/src/main -confl int-base3.cpp

posnat-to-int-base3:
	/usr/ccs/lib/cpp -P posnat-to-int-base3.cim posnat-to-int-base3.cpp
	/users/demons/contejea/cime/src/main -confl posnat-to-int-base3.cpp

div:
	/usr/ccs/lib/cpp -P div.cim div.cpp
	/users/demons/contejea/cime/src/main -confl div.cpp
